# Generated by Django 4.0 on 2022-02-08 09:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('service_feedback', models.TextField(null=True)),
            ],
        ),
    ]
