# Generated by Django 4.0 on 2022-02-08 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_feedback_rating_feedback_user_alter_feedback_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
