# Generated by Django 4.0 on 2022-02-04 08:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('service_description', models.TextField(null=True)),
                ('service_photo', models.ImageField(null=True, upload_to='static/uploads/% Y/% m/% d/')),
                ('service_price', models.FloatField()),
                ('service_created_date', models.DateField(auto_now_add=True, null=True)),
                ('service_categoty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.category')),
            ],
        ),
    ]
