# Generated by Django 4.0 on 2022-02-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_location',
            field=models.CharField(choices=[('Kathmandu', 'Kathmandu'), ('Bhaktapur', 'Bhaktapur'), ('Lalitpur', 'Lalitpur')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_photo',
            field=models.ImageField(null=True, upload_to='static/uploads'),
        ),
    ]
