# Generated by Django 4.0 on 2022-02-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0009_alter_service_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_price',
            field=models.IntegerField(null=True),
        ),
    ]
