# Generated by Django 4.0 on 2022-02-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0010_alter_service_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
