# Generated by Django 4.0 on 2022-02-13 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0011_alter_service_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='user',
        ),
    ]
