<<<<<<< HEAD
# Generated by Django 4.0 on 2022-02-07 15:05

import django.core.validators
from django.db import migrations, models
=======
# Generated by Django 4.0 on 2022-02-07 12:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
>>>>>>> 9e3cca5b061039e2e9940c673a71d882929e213a


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        ('professionals', '0007_alter_service_service_photo'),
        ('auth', '0012_alter_user_first_name_max_length'),
>>>>>>> 9e3cca5b061039e2e9940c673a71d882929e213a
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('product_feedback', models.TextField()),
=======
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('total_price', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], max_length=200, null=True)),
                ('contact_no', models.CharField(max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(10)])),
                ('contact_address', models.CharField(max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='professionals.service')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
>>>>>>> 9e3cca5b061039e2e9940c673a71d882929e213a
            ],
        ),
    ]
