# Generated by Django 4.0 on 2021-12-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=25)),
                ('confirm_password', models.CharField(max_length=25)),
            ],
        ),
    ]
