# Generated by Django 4.0 on 2021-12-20 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSignUp',
        ),
    ]
