# Generated by Django 4.0 on 2021-12-20 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSignUp',
            new_name='User',
        ),
    ]
