# Generated by Django 4.0 on 2021-12-20 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0004_rename_usersignup_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserSignUp',
        ),
    ]
