# Generated by Django 4.0 on 2021-12-21 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0006_remove_usersignup_password2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersignup',
            old_name='password1',
            new_name='password',
        ),
    ]
