# Generated by Django 4.0 on 2021-12-21 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0007_rename_password1_usersignup_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersignup',
            old_name='password',
            new_name='password1',
        ),
    ]
