# Generated by Django 4.0 on 2021-12-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0008_rename_password_usersignup_password1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='password1',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
