# Generated by Django 4.0 on 2021-12-21 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0009_alter_usersignup_password1_alter_usersignup_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSignUp',
        ),
    ]
