# Generated by Django 4.0 on 2021-12-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0011_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('password1', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
