# Generated by Django 4.0 on 2022-01-15 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0015_alter_profile_profile_pic_userotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserOTP',
        ),
    ]
