# Generated by Django 4.0 on 2022-02-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0019_profile_forget_password_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
